services:
  db_postgres:
    image: postgres:latest
    container_name: postgrescaso2
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: basepostgre
    ports:
      - "5432:5432"
    networks:
      - data_network

  db_mysql:
    image: mysql:latest
    container_name: mysqlcaso2
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: Dynamic
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    networks:
      - data_network
  dashboard_bi:
    image: metabase/metabase:latest
    container_name: metabase_gerencial
    ports:
      - "3000:3000"
    networks:
      - data_network
  etl_process:
    image: python:3.10-slim
    container_name: etl_unificador
    volumes:
      - ./etl_script:/app
    working_dir: /app
    depends_on:
      - db_postgres
      - db_mysql
    networks:
      - data_network
networks:
  data_network:
    driver: bridge


